### ISSUE TITLE
Problemas con la mision El desafio del aspirante

### ISSUE THREAD

**Issue by Kathycaptor** [ClownedDev/Release-Project#2]
https://es.wowhead.com/quest=13680/el-desaf%C3%ADo-del-aspirante
Tengo problemas con esta misión después de vencer al campeón no se completa la misión para poder entregarla mi personaje es Aleja
![WoWScrnShot_120220_090257](https://user-images.githubusercontent.com/75381064/100894645-b57e0c00-348a-11eb-85ef-a8e30a4066ab.jpg)

**Comment by ClownedDev** [comment]
Quest FIX, funciona de forma normal. Testeado 24/02
