### ISSUE TITLE
Mision bug ¡Rendios!

### ISSUE THREAD

**Issue by Habichuela** [ClownedDev/Release-Project#3]
https://es.wowhead.com/quest=24868/rend%C3%ADos
La mision despues de aceptada me envia con un npc a buscar un NAGA, pero en una parte del mapa se queda detenido y no avanza (IMAGEN 1), luego al final donde se debe llegar aparece un circulo o semicirculo negro (IMAGEN 2)

IMAGEN 1

![IMAGEN 1](https://user-images.githubusercontent.com/75814199/101838007-e6ef7b00-3b0d-11eb-8a9a-ff177541b6ee.jpg)

IMAGEN 2

![IMAGEN 2](https://user-images.githubusercontent.com/75814199/101838027-efe04c80-3b0d-11eb-9b0c-204ab425204b.jpg)

**Comment by ClownedDev** [comment]
Quest Fix trabaja sin problemas.
