### ISSUE TITLE
Mision Bug: Retenidos por la plaga

### ISSUE THREAD

**Issue by Habichuela** [ClownedDev/Release-Project#4]
Hola un buen día, reporto la misión en el asunto, no permite tomar los peones luego de ser liberados de las telarañas explico en imágenes.

**IMAGEN 1** 
Esta es la misión y como se debe ver el peón.

![IMAGEN 1](https://user-images.githubusercontent.com/75814199/101990266-fdafe200-3c73-11eb-8d70-27e0f6370c16.jpg)

**IMAGEN 2** 
Este es el peón que se debe liberar( busque por todas partes y no encontré nada interactivo) de las telarañas 

![IMAGEN 2](https://user-images.githubusercontent.com/75814199/101990287-1ae4b080-3c74-11eb-9b4b-b7d0c11c2890.jpg)

**IMAGEN 3**
Se evidencia que una vez la telaraña es disuelta no aparece nada, ni el peón.

![IMAGEN 3](https://user-images.githubusercontent.com/75814199/101990313-48315e80-3c74-11eb-826a-12f7746102fe.jpg)

**IMAGEN 4**
Este NPC es el que sale en ocasiones cuando la telaraña es disuelta.

![IMAGEN 4](https://user-images.githubusercontent.com/75814199/101990400-dad1fd80-3c74-11eb-9e2f-2c60324f5305.jpg)

Muchas gracias.

**Comment by ClownedDev** [comment]
La quest libera tanto peones como guerreros cautivos que te ayudan a pelear, el % de que te salga un peon al eliminar la telaraña es de 5% pero aumentamos la cantidad de telarañas para que sea mas dinamico.
