### ISSUE TITLE
Mamut de Tundra de Viajero Bug

### ISSUE THREAD

**Issue by javierdls** [ClownedDev/Release-Project#5]
No se pueden expulsar los intendentes para dar montura a dos jugadores mas. 

![Captura](https://user-images.githubusercontent.com/72824834/101993208-2abdbe00-3c8f-11eb-867e-ab1f1b3d0329.PNG)

**Comment by ClownedDev** [comment]
Esa montura viene con 2 vendedores no se pueden bajar.
