### ISSUE TITLE
Lo que nos depara el futuro ( quest=8286 )

### ISSUE THREAD

**Issue by Alejandro779** [ClownedDev/Release-Project#6]
La misión simplemente no aparece para hacerse. ID Misión : 8286
![Mision bug](https://user-images.githubusercontent.com/75956529/102027543-43a39d80-3d7b-11eb-9eb2-e628f9c07e39.png)

**Comment by Alejandro779** [comment]
alguien esta atendiendo

**Comment by ClownedDev** [comment]
Quet eliminada completamente en parches superiores a wow Clasic.
