### ISSUE TITLE
Bug Mision / El esclavo del cazador de monos

### ISSUE THREAD

**Issue by nekroz5201** [ClownedDev/Release-Project#7]
Esta Mision esta bug , Basicamente mato a los que me dice pero no me cuenta la mision 
![Capture](https://user-images.githubusercontent.com/76070112/102265388-cfd9d000-3ef5-11eb-8038-2652fb502702.PNG)

**Comment by nekroz5201** [comment]
https://es.wowhead.com/quest=12529/el-esclavo-del-cazador-de-monos

**Comment by ClownedDev** [comment]
Quest funcional, tienen que matar a los destrero callonudillo [Gorilas negros]
