### ISSUE TITLE
Problema con habilidad del druida Carga Feral (felino)

### ISSUE THREAD

**Issue by abelSW** [ClownedDev/Release-Project#8]
Hola 
quisiera informar que hay un mal funcionamiento con la habilidad Carga Feral (felina). Es una habilidad del druida feral que consiste en que el usuario druida salta hacia el objetivo y dejarlo estoneado por pocos segundos. El problema es que se supone que debe dejar al druida forma feral automáticamente atacando la espalda de ese objetivo; pero, lo que en realidad hace, es dejar espalda con espalda al usuario druida y al objetivo, lo cual obliga a voltear la cámara y al pj para poder atacar.

**Comment by ClownedDev** [comment]
La habilidad de cargar feral del druida no trabaja de esa manera, la camara la tienes que direcionar manualmente. Aca un video referencial https://www.youtube.com/watch?v=i3v5rLeqric
